### ISSUE TITLE
iosxr_config replace: config uploads wrong config to device when targeting multiple systems

### ISSUE THREAD

**Issue by shanerenshawaus** [ansible-collections/cisco.iosxr#67] opened 2020-07-22 22:35 UTC
##### SUMMARY

When using the iosxr_config replace:config option the module appears to always upload the same config to all devices. When runnin the same playbook through with a single host selected the module successfully uploads and applies the configuration however results become unstable when targeting a group with multiple hosts
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

iosxr
##### ANSIBLE VERSION

```paste below
ansible 2.9.9 
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/srenshaw/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules'] 
  ansible python module location = /home/srenshaw/.local/lib/python2.7/site-packages/ansible
  executable location = /home/srenshaw/.local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING = explicit
DEFAULT_JINJA2_EXTENSIONS= jinja2.ext.with_
HOST_KEY_CHECKING = False
INTERPRETER_PYTHON = auto
```

##### STEPS TO REPRODUCE

```yaml
[iosxr]
icf01
icf02
icf03
icf04

[dc2]
icf0[3:4]

[dc1]
icf0[1:2]

[dcx:children]
dc1
dc2


---
  - name: Generate and Commit Gold Config
    block:
        - name: Generate Golden Master
          template:
            src: "{{ os }}.j2"
            dest: "{{ config_dir }}/{{ inventory_hostname }}_golden_master.cfg"
          check_mode: no

        - name: Commit Golden Master
          iosxr_config:
            src: "{{ config_dir }}/{{ inventory_hostname }}_golden_master.cfg"
            replace: config
            provider: "{{ provider }}"
          when: gold_commit
```

##### EXPECTED RESULTS

When applying the above playbook devices should recieve their matching configurations files. eg:
icf03 - output/icf03_golden_master.cfg
icf04 - output/icf04_golden_master.cfg

##### ACTUAL RESULTS

When applied at the group level the configs are not applied properly and cause the devices to recieve the wrong config eg:
icf03 - output/icf03_golden_master.cfg
icf04 - output/icf03_golden_master.cfg

As a results some devices become unavailable as the wrong configs are pushed. in the above example icf04 becomes unavailable as it is now running icf03's config. in the below trimmed outputs you can see that icf03's diff indicates the first change will be to tacacs however the config going to icf04 wants to change the hostname first as it is recieving the wrong configuration

```paste below
<10.69.2.19> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1595456877.41-17076-17009141884094/ > /dev/null 2>&1 && sleep 0'
changed: [icf03] => {
    "changed": true, 
    "commands": [
        "load harddisk:/ansible_config.txt"
    ], 
    "diff": {
        "prepared": "Building configuration...\n!! IOS XR Configuration 7.0.2\n   tacacs-server 
<10.69.2.99> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1595456877.37-17077-54185194722578/ > /dev/null 2>&1 && sleep 0'
changed: [icf04] => {
    "changed": true, 
    "commands": [
        "load harddisk:/ansible_config.txt"
    ], 
    "diff": {
        "prepared": "Building configuration...\n!! IOS XR Configuration 7.0.2\n<- hostname DC2-EP20-ICF04\n+> hostname DC2-EP19-ICF03\n   t
```
Trimmed copy of icf03_golden_master.cfg
```paste below
hostname DC2-EP19-ICF03
---- Removed ----
tacacs source-interface MgmtEth0/RP0/CPU0/0 vrf Management
tacacs-server host 10.64.32.13 port 49
---- Removed ----
```

Trimmed copy of icf04_golden_master.cfg
```paste below
hostname DC2-EP20-ICF04
---- Removed ----
tacacs source-interface MgmtEth0/RP0/CPU0/0 vrf Management
tacacs-server host 10.64.32.13 port 49
---- Removed ----
```
Issue can be mittigated by setting the throttle:1 option to the task. this results in routers recieving the correct config
```paste below
  - name: Generate and Commit Gold Config
    block:
        - name: Generate Golden Master
          template:
            src: "{{ os }}.j2"
            dest: "{{ config_dir }}/{{ inventory_hostname }}_golden_master.cfg"
          check_mode: no

        - name: Commit Golden Master
          iosxr_config:
            src: "{{ config_dir }}/{{ inventory_hostname }}_golden_master.cfg"
            replace: config
            provider: "{{ provider }}"
          when: gold_commit
          throttle: 1
```

**Comment by JaakkoRautanen** [comment] 2022-05-31 09:59
This issue seems to be open still. I'm having this one too. Setting throttle to 1 slows down running playbook. Any idea if this will be fixed in the near future?

**Comment by JaakkoRautanen** [comment] 2022-06-10 09:55
Is the root cause of this issue because of iosxr_config - module uses /tmp/ansible_config.txt as hardcoded in the code?
https://github.com/ansible-collections/cisco.iosxr/blob/main/plugins/modules/iosxr_config.py#L278

Imagine running this code in parallel for multiple routers. They all use same file name and write at the same time.
This is by the way reason why you cannot run iosxr_config by multiple users on the same machine. You will get error like this: `"module_stderr": "[Errno 13] Permission denied: '/tmp/ansible_config.txt'"`

This is because of if user1 has run the playbook this file already exists and is owned by user1. When user2 runs playbook after that it leads to permission error.

**Comment by JaakkoRautanen** [comment] 2022-06-28 05:20
Hi @KB-perByte, yes it does.

**Comment by ashwini-mhatre** [comment] 2022-11-21 09:23
@shanerenshawaus PR is up https://github.com/ansible-collections/cisco.iosxr/pull/279 could you please test it and confirm?

**Comment by ashwini-mhatre** [comment] 2022-11-24 18:39
@shanerenshawaus any update on this?

**Closed** 2022-11-24 18:40 UTC
Labels: waiting_on_author
