### ISSUE TITLE
When executing config changes to IOSXR device, the resulting commit record on the device does not have the label

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.iosxr#314] opened 2023-01-10 21:37 UTC
##### SUMMARY

When executing config changes to IOSXR device with the cisco.iosxr.iosxr_bgp_neighbor_address_family module with the var “ansible_iosxr_commit_label” provided in the required string format, the resulting commit record on the device does not have the label. Tested on ASR9k and NCS devices. Label is applied correctly from other example IOSXR modules to same devices, like iosxr_interfaces.  This issue is specific to Ansible-core 2.13 and 2.14.0. The commit_label is passing fine with 2.9 or 2.12. All tests were done with cisco.iosxr collection version 4.0.2

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.iosxr.iosxr_bgp_neighbor_address_family

##### ANSIBLE VERSION

```paste below

(ansible213_venv) REDACTED@REDACTED-dev:~/REDACTED/gitlab/sips/ansible-playbooks/REDACTED$ ansible --version
ansible [core 2.13.4]
  config file = /media/REDACTED/gitlab/sips/ansible-playbooks/REDACTED/ansible.cfg
  configured module search path = ['/home/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/REDACTED/ansible213_venv/lib/python3.10/site-packages/ansible
  ansible collection location = /home/REDACTED/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/REDACTED/ansible213_venv/bin/ansible
  python version = 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below

(ansible213_venv) REDACTED@REDACTED-dev:~/REDACTED/gitlab/sips/ansible-playbooks/REDACTED$ ansible-galaxy collection list cisco.iosxr

# /home/REDACTED/ansible213_venv/lib/python3.10/site-packages/ansible_collections
Collection  Version
----------- -------
cisco.iosxr 4.0.2

```

##### CONFIGURATION

```paste below

(ansible213_venv) REDACTED@REDACTED-dev:~/REDACTED/gitlab/sips/ansible-playbooks/REDACTED$ ansible-config dump --only-changed
DEFAULT_LOG_PATH(/media/REDACTED/gitlab/sips/ansible-playbooks/REDACTED/ansible.cfg) = /home/REDACTED/REDACTED/ansible_job_logs/ansible_log
(ansible213_venv) REDACTED@REDACTED-dev:~/REDACTED/gitlab/sips/ansible-playbooks/REDACTED$

```

##### OS / ENVIRONMENT

RP/0/RSP1/CPU0:ASR9K-01#show version
Tue Nov 22 10:50:25.646 GMT

Cisco IOS XR Software, Version 6.5.3[Default]
Copyright (c) 2019 by Cisco Systems, Inc.

ROM: System Bootstrap, Version 10.65(c) 1994-2014 by Cisco Systems,  Inc.

ASR9K-01 uptime is 1 year, 20 weeks, 4 days, 20 hours, 59 minutes
System image file is "disk0:asr9k-os-mbi-6.5.3/0x100305/mbiasr9k-rsp3.vm"

cisco ASR9K Series (Intel 686 F6M14S4) processor with 16777216K bytes of memory.
Intel 686 F6M14S4 processor at 1904MHz, Revision 2.174
ASR-9010 8 Line Card Slot Chassis with V3 AC PEM
RP/0/RP0/CPU0:NCS55A1-01#show version
Tue Nov 22 16:50:26.158 GMT
Cisco IOS XR Software, Version 7.2.2
Copyright (c) 2013-2021 by Cisco Systems, Inc.

Build Information:
 Built By     : ingunawa
 Built On     : Mon Jan 25 21:52:54 PST 2021
 Built Host   : iox-ucs-013
 Workspace    : /auto/srcarchive15/prod/7.2.2/ncs5500/ws
 Version      : 7.2.2
 Location     : /opt/cisco/XR/packages/
 Label        : 7.2.2

cisco NCS-5500 () processor

##### STEPS TO REPRODUCE

```yaml

---
- set_fact:
number_of_commit_labels: "{{ number_of_commit_labels | int + 1 }}"

- name: Configure BGP Neighbor Address Family
vars:
disable_default_comment: true
ansible_iosxr_commit_label: "CR{{ CR_number }}_bgp_{{ number_of_commit_labels }}"
cisco.iosxr.iosxr_bgp_neighbor_address_family:
config: "{{ network_service_config['bgp_neighbor_address_family'] }}"
state: "{{ network_service_config['state'] }}"
register: bgp_neighbor_address_family_config

```

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above →

After successful commit, the commit history on the IOSXR device will show the custom commit label instead of the default commit id. Example:

RP/0/RP0/CPU0:NCS55A1-01#show configuration commit list | i CR
Tue Nov 22 16:55:09.145 GMT
9    CR000000117_int_1     useridx  vty0:node0_RP0_CPU  CLI         Tue Nov 15 16:31:16 2022

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra
verbosity (-vvvv) →

Example of current commit that fails to apply the commit label:

RP/0/RP0/CPU0:NCS55A1-01#show configuration commit list
Tue Nov 22 16:56:32.390 GMT
SNo. Label/ID              User      Line                Client      Time Stamp
~~~~ ~~~~~~~~              ~~~~      ~~~~                ~~~~~~      ~~~~~~~~~~
1    1000084655            REDACTED  vty1:node0_RP0_CPU  CLI         Thu Nov 17 15:01:05 2022

<!--- Paste verbatim command output between quotes -->
```paste below

```

**Comment by ashwini-mhatre** [comment] 2023-01-13 10:57
@digitalfiend64 I am not able to reproduce with
```
RP/0/RP0/CPU0:iosxr1#show version
Fri Jan 13 10:54:23.114 UTC
Cisco IOS XR Software, Version 7.0.2
Copyright (c) 2013-2020 by Cisco Systems, Inc.

Build Information:
 Built By     : ahoang
 Built On     : Fri Mar 13 22:27:54 PDT 2020
 Built Host   : iox-ucs-029
 Workspace    : /auto/srcarchive15/prod/7.0.2/xrv9k/ws
 Version      : 7.0.2
 Location     : /opt/cisco/XR/packages/
 Label        : 7.0.2

cisco IOS-XRv 9000 () processor
System uptime is 6 weeks 23 hours 35 minutes

RP/0/RP0/CPU0:iosxr1#

```

**Comment by dwnetautomation** [comment] 2023-01-16 18:51
I confirmed this issue is present on cisco.iosxr 4.0.2 for cisco.iosxr.iosxr_bgp_neighbor_address_family with IOSXR version 6.5.3:

RP/0/RSP1/CPU0:ASR9K-01#show version
Mon Jan 16 12:45:51.398 GMT

Cisco IOS XR Software, Version 6.5.3[Default]
Copyright (c) 2019 by Cisco Systems, Inc.

Also, same issue exists with cisco.iosxr.iosxr_lag_interfaces role on cisco.iosxr collection 4.0.3. Seems to be global to the cisco.iosxr collection as opposed to role specific.

**Comment by ashwini-mhatre** [comment] 2023-01-25 09:39
@digitalfiend64 We have also tested this on physical router 7.10.0 which is latest one PF below logs


```
(ansible_collections) prramoor @ ~/Ansible/iosxr $ ansible-playbook -i inventory.yaml iosxr.yaml -vvvvv 
ansible-playbook [core 2.13.5] (detached HEAD 09cf0ed123) last updated 2023/01/24 16:52:57 (GMT +550)
  config file = /Users/prramoor/Ansible/iosxr/ansible.cfg
  configured module search path = ['/Users/prramoor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/prramoor/Ansible/iosxr/ansible/lib/ansible
  ansible collection location = /Users/prramoor/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/prramoor/Ansible/iosxr/ansible/bin/ansible-playbook
  python version = 3.8.0 (default, Apr 13 2020, 16:49:15) [Clang 11.0.3 (clang-1103.0.32.29)]
  jinja version = 3.0.3
  libyaml = True
Using /Users/prramoor/Ansible/iosxr/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /Users/prramoor/Ansible/iosxr/inventory.yaml as it did not pass its verify_file() method
script declined parsing /Users/prramoor/Ansible/iosxr/inventory.yaml as it did not pass its verify_file() method
Parsed /Users/prramoor/Ansible/iosxr/inventory.yaml inventory source with yaml plugin
Loading collection cisco.iosxr from /Users/prramoor/Ansible/iosxr/collections/ansible_collections/cisco/iosxr
Loading callback plugin default of type stdout, v2.0 from /Users/prramoor/Ansible/iosxr/ansible/lib/ansible/plugins/callback/default.py
Attempting to use 'default' callback.
Skipping callback 'default', as we already have a stdout callback.
Attempting to use 'junit' callback.
Attempting to use 'minimal' callback.
Skipping callback 'minimal', as we already have a stdout callback.
Attempting to use 'oneline' callback.
Skipping callback 'oneline', as we already have a stdout callback.
Attempting to use 'tree' callback.

PLAYBOOK: iosxr.yaml ********************************************************************************************************************************************************************
Positional arguments: iosxr.yaml
verbosity: 5
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/Users/prramoor/Ansible/iosxr/inventory.yaml',)
forks: 5
1 plays in iosxr.yaml

PLAY [IOS XR comment and commit config testing on 7.3.1 image] **************************************************************************************************************************
META: ran handlers

TASK [Show version] *********************************************************************************************************************************************************************
task path: /Users/prramoor/Ansible/iosxr/iosxr.yaml:6
Loading collection ansible.netcommon from /Users/prramoor/Ansible/iosxr/collections/ansible_collections/ansible/netcommon
<10.64.78.169> attempting to start connection
<10.64.78.169> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /Users/prramoor/Ansible/iosxr/ansible/bin/ansible-connection
<10.64.78.169> local domain socket does not exist, starting it
<10.64.78.169> control socket path is /Users/prramoor/.ansible/pc/1fe240443e
<10.64.78.169> Loading collection ansible.netcommon from /Users/prramoor/Ansible/iosxr/collections/ansible_collections/ansible/netcommon
<10.64.78.169> Loading collection cisco.iosxr from /Users/prramoor/Ansible/iosxr/collections/ansible_collections/cisco/iosxr
<10.64.78.169> local domain socket listeners started successfully
<10.64.78.169> loaded cliconf plugin ansible_collections.cisco.iosxr.plugins.cliconf.iosxr from path /Users/prramoor/Ansible/iosxr/collections/ansible_collections/cisco/iosxr/plugins/cliconf/iosxr.py for network_os cisco.iosxr.iosxr
<10.64.78.169> ssh type is set to auto
<10.64.78.169> autodetecting ssh_type
<10.64.78.169> ssh type is now set to libssh
<10.64.78.169> 
<10.64.78.169> local domain socket path is /Users/prramoor/.ansible/pc/1fe240443e
<10.64.78.169> Using network group action cisco.iosxr.iosxr for cisco.iosxr.iosxr_command
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: enabled
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: found cisco.iosxr.iosxr_command  at /Users/prramoor/Ansible/iosxr/collections/ansible_collections/cisco/iosxr/plugins/modules/iosxr_command.py
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: running cisco.iosxr.iosxr_command
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: complete
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: Result: {'changed': False, 'stdout': ['Cisco IOS XR Software, Version 7.10.1\nCopyright (c) 2013-2022 by Cisco Systems, Inc.\n\nBuild Information:\n Built By     :\n Built On     : Mon Dec 26 17:19:00 IST 2022\n Built Host   :\n Workspace    : \n Version      : 7.10.1\n Location     : /opt/cisco/XR/packages/\n Label        : 7.10.1\n\ncisco NCS-5500 () processor\nSystem uptime is 3 hours 40 minutes'], 'stdout_lines': [['Cisco IOS XR Software, Version 7.10.1', 'Copyright (c) 2013-2022 by Cisco Systems, Inc.', '', 'Build Information:', ' Built By     :', ' Built On     : Mon Dec 26 17:19:00 IST 2022', ' Built Host   : ', ' Workspace    : ', ' Version      : 7.10.1', ' Location     : /opt/cisco/XR/packages/', ' Label        : 7.10.1', '', 'cisco NCS-5500 () processor', 'System uptime is 3 hours 40 minutes']], 'invocation': {'module_args': {'commands': ['show version'], 'match': 'all', 'retries': 10, 'interval': 1, 'wait_for': None}}, '_ansible_parsed': True}
ok: [10.64.78.169] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show version"
            ],
            "interval": 1,
            "match": "all",
            "retries": 10,
            "wait_for": null
        }
    },
    "stdout": [
        "Cisco IOS XR Software, Version 7.10.1\nCopyright (c) 2013-2022 by Cisco Systems, Inc.\n\nBuild Information:\n Built By     :\n Built On     : Mon Dec 26 17:19:00 IST 2022\n Built Host   :\n Workspace    : \n Version      : 7.10.1\n Location     : /opt/cisco/XR/packages/\n Label        : 7.10.1\n\ncisco NCS-5500 () processor\nSystem uptime is 3 hours 40 minutes"
    ],
    "stdout_lines": [
        [
            "Cisco IOS XR Software, Version 7.10.1",
            "Copyright (c) 2013-2022 by Cisco Systems, Inc.",
            "",
            "Build Information:",
            " Built By     :",
            " Built On     : Mon Dec 26 17:19:00 IST 2022",
            " Built Host   :",
            " Workspace    :",
            " Version      : 7.10.1",
            " Location     : /opt/cisco/XR/packages/",
            " Label        : 7.10.1",
            "",
            "cisco NCS-5500 () processor",
            "System uptime is 3 hours 40 minutes"
        ]
    ]
}

TASK [Setup] ****************************************************************************************************************************************************************************
task path: /Users/prramoor/Ansible/iosxr/iosxr.yaml:10
Loading collection ansible.netcommon from /Users/prramoor/Ansible/iosxr/collections/ansible_collections/ansible/netcommon
<10.64.78.169> attempting to start connection
<10.64.78.169> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /Users/prramoor/Ansible/iosxr/ansible/bin/ansible-connection
<10.64.78.169> found existing local domain socket, using it!
<10.64.78.169> invoked shell using ssh_type: libssh
<10.64.78.169> ssh connection done, setting terminal
<10.64.78.169> loaded terminal plugin for network_os cisco.iosxr.iosxr
<10.64.78.169> firing event: on_open_shell()
<10.64.78.169> ssh connection has completed successfully
<10.64.78.169> updating play_context for connection
<10.64.78.169> 
<10.64.78.169> local domain socket path is /Users/prramoor/.ansible/pc/1fe240443e
<10.64.78.169> Using network group action cisco.iosxr.iosxr for cisco.iosxr.iosxr_lag_interfaces
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: enabled
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: found cisco.iosxr.iosxr_lag_interfaces  at /Users/prramoor/Ansible/iosxr/collections/ansible_collections/cisco/iosxr/plugins/modules/iosxr_lag_interfaces.py
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: running cisco.iosxr.iosxr_lag_interfaces
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: complete
<10.64.78.169> ANSIBLE_NETWORK_IMPORT_MODULES: Result: {'changed': True, 'commands': ['interface Bundle-Ether12', 'lacp mode active', 'interface GigabitEthernet0/0/0/11', 'bundle id 12 mode passive', 'interface GigabitEthernet0/0/0/10', 'bundle id 12 mode passive'], 'before': [{'members': [{'member': 'GigabitEthernet0/0/0/8', 'mode': 'passive'}, {'member': 'GigabitEthernet0/0/0/9', 'mode': 'passive'}], 'mode': 'active', 'name': 'Bundle-Ether11'}], 'after': [{'members': [{'member': 'GigabitEthernet0/0/0/8', 'mode': 'passive'}, {'member': 'GigabitEthernet0/0/0/9', 'mode': 'passive'}], 'mode': 'active', 'name': 'Bundle-Ether11'}, {'members': [{'member': 'GigabitEthernet0/0/0/10', 'mode': 'passive'}, {'member': 'GigabitEthernet0/0/0/11', 'mode': 'passive'}], 'mode': 'active', 'name': 'Bundle-Ether12'}], 'invocation': {'module_args': {'config': [{'name': 'Bundle-Ether12', 'mode': 'active', 'members': [{'member': 'GigabitEthernet0/0/0/11', 'mode': 'passive'}, {'member': 'GigabitEthernet0/0/0/10', 'mode': 'passive'}], 'links': None, 'load_balancing_hash': None}], 'state': 'merged', 'running_config': None}}, '_ansible_parsed': True}
changed: [10.64.78.169] => {
    "after": [
        {
            "members": [
                {
                    "member": "GigabitEthernet0/0/0/8",
                    "mode": "passive"
                },
                {
                    "member": "GigabitEthernet0/0/0/9",
                    "mode": "passive"
                }
            ],
            "mode": "active",
            "name": "Bundle-Ether11"
        },
        {
            "members": [
                {
                    "member": "GigabitEthernet0/0/0/10",
                    "mode": "passive"
                },
                {
                    "member": "GigabitEthernet0/0/0/11",
                    "mode": "passive"
                }
            ],
            "mode": "active",
            "name": "Bundle-Ether12"
        }
    ],
    "before": [
        {
            "members": [
                {
                    "member": "GigabitEthernet0/0/0/8",
                    "mode": "passive"
                },
                {
                    "member": "GigabitEthernet0/0/0/9",
                    "mode": "passive"
                }
            ],
            "mode": "active",
            "name": "Bundle-Ether11"
        }
    ],
    "changed": true,
    "commands": [
        "interface Bundle-Ether12",
        "lacp mode active",
        "interface GigabitEthernet0/0/0/11",
        "bundle id 12 mode passive",
        "interface GigabitEthernet0/0/0/10",
        "bundle id 12 mode passive"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "links": null,
                    "load_balancing_hash": null,
                    "members": [
                        {
                            "member": "GigabitEthernet0/0/0/11",
                            "mode": "passive"
                        },
                        {
                            "member": "GigabitEthernet0/0/0/10",
                            "mode": "passive"
                        }
                    ],
                    "mode": "active",
                    "name": "Bundle-Ether12"
                }
            ],
            "running_config": null,
            "state": "merged"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ******************************************************************************************************************************************************************************
10.64.78.169               : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   




```

```
RP/0/RP0/CPU0:NCS5500#show configuration commit list 2
Tue Jan 24 11:54:26.828 UTC
SNo. Label/ID              User      Line                Client      Time Stamp
~~~~ ~~~~~~~~              ~~~~      ~~~~                ~~~~~~      ~~~~~~~~~~
1    commit_label_test_1   root      vty0:node0_RP0_CPU  CLI         Tue Jan 24 11:51:33 2023
2    commit_label_test     root      vty0:node0_RP0_CPU  CLI         Tue Jan 24 11:45:21 2023
RP/0/RP0/CPU0:NCS5500#
RP/0/RP0/CPU0:NCS5500#
RP/0/RP0/CPU0:NCS5500#
RP/0/RP0/CPU0:NCS5500#
RP/0/RP0/CPU0:NCS5500#
RP/0/RP0/CPU0:NCS5500#show version 
Tue Jan 24 11:54:32.489 UTC
Cisco IOS XR Software, Version 7.10.1
Copyright (c) 2013-2022 by Cisco Systems, Inc.

Build Information:
 Built By     : 
 Built On     : Mon Dec 26 17:19:00 IST 2022
 Built Host   : 
 Workspace    : 
 Version      : 7.10.1
 Location     : /opt/cisco/XR/packages/
 Label        : 7.10.1

cisco NCS-5500 () processor
System uptime is 3 hours 43 minutes

RP/0/RP0/CPU0:NCS5500#

```

**Comment by ashwini-mhatre** [comment] 2023-02-20 13:42
We have not able to reproduce with 6.5.3 iosxr here is the logs

```
- name: populate af in nbrs
  hosts: iosxr
  gather_facts: false
  tasks:
    - name: Parse externally provided BGP config
      register: result
      connection: ansible.netcommon.network_cli
      vars:
        ansible_iosxr_commit_label: commit_label_test_nbr
      cisco.iosxr.iosxr_bgp_neighbor_address_family:
        config:
          as_number: 1
          neighbors:
            - neighbor_address: 1.1.1.1
              address_family:
                - afi: ipv4
                  safi: unicast
                  soft_reconfiguration:
                    inbound:
                      always: true
        state: merged
```
```
PLAYBOOK: iosxr.yaml ********************************************************************************************************************************************************************

Positional arguments: iosxr.yaml

verbosity: 5

connection: smart

timeout: 10

become_method: sudo

tags: ('all',)

inventory: ('/Users/prramoor/Ansible/iosxr/inventory.yaml',)

forks: 5

1 plays in iosxr.yaml

 

PLAY [IOS XR comment and commit config testing on 7.3.1 image] **************************************************************************************************************************

META: ran handlers

 

TASK [Parse externally provided BGP config] *********************************************************************************************************************************************

task path: /Users/prramoor/Ansible/iosxr/iosxr.yaml:56

Loading collection ansible.netcommon from /Users/prramoor/Ansible/iosxr/collections/ansible_collections/ansible/netcommon

<10.104.99.162> attempting to start connection

<10.104.99.162> using connection plugin ansible.netcommon.network_cli

Found ansible-connection at path /Users/prramoor/Ansible/iosxr/ansible/bin/ansible-connection

<10.104.99.162> local domain socket does not exist, starting it

<10.104.99.162> control socket path is /Users/prramoor/.ansible/pc/ce6abdbd47

<10.104.99.162> Loading collection ansible.netcommon from /Users/prramoor/Ansible/iosxr/collections/ansible_collections/ansible/netcommon

<10.104.99.162> Loading collection cisco.iosxr from /Users/prramoor/Ansible/iosxr/collections/ansible_collections/cisco/iosxr

<10.104.99.162> local domain socket listeners started successfully

<10.104.99.162> loaded cliconf plugin ansible_collections.cisco.iosxr.plugins.cliconf.iosxr from path /Users/prramoor/Ansible/iosxr/collections/ansible_collections/cisco/iosxr/plugins/cliconf/iosxr.py for network_os cisco.iosxr.iosxr

<10.104.99.162> ssh type is set to auto

<10.104.99.162> autodetecting ssh_type

<10.104.99.162> ssh type is now set to libssh

<10.104.99.162> 

<10.104.99.162> local domain socket path is /Users/prramoor/.ansible/pc/ce6abdbd47

<10.104.99.162> Using network group action cisco.iosxr.iosxr for cisco.iosxr.iosxr_bgp_neighbor_address_family

<10.104.99.162> ANSIBLE_NETWORK_IMPORT_MODULES: enabled

<10.104.99.162> ANSIBLE_NETWORK_IMPORT_MODULES: found cisco.iosxr.iosxr_bgp_neighbor_address_family  at /Users/prramoor/Ansible/iosxr/collections/ansible_collections/cisco/iosxr/plugins/modules/iosxr_bgp_neighbor_address_family.py

<10.104.99.162> ANSIBLE_NETWORK_IMPORT_MODULES: running cisco.iosxr.iosxr_bgp_neighbor_address_family

<10.104.99.162> ANSIBLE_NETWORK_IMPORT_MODULES: complete

<10.104.99.162> ANSIBLE_NETWORK_IMPORT_MODULES: Result: {'commands': ['router bgp 1', 'neighbor 1.1.1.1', 'address-family ipv4 unicast', 'soft-reconfiguration inbound always'], 'before': {'as_number': '1'}, 'after': {'as_number': '1', 'neighbors': [{'neighbor_address': '1.1.1.1', 'address_family': [{'afi': 'ipv4', 'safi': 'unicast', 'soft_reconfiguration': {'inbound': {'always': True}}}]}]}, 'changed': True, 'invocation': {'module_args': {'config': {'as_number': '1', 'neighbors': [{'neighbor_address': '1.1.1.1', 'address_family': [{'afi': 'ipv4', 'safi': 'unicast', 'soft_reconfiguration': {'inbound': {'always': True, 'set': None, 'inheritance_disable': None}}, 'aigp': None, 'allowas_in': None, 'as_override': None, 'bestpath_origin_as_allow_invalid': None, 'capability_orf_prefix': None, 'default_originate': None, 'long_lived_graceful_restart': None, 'maximum_prefix': None, 'multipath': None, 'next_hop_self': None, 'next_hop_unchanged': None, 'optimal_route_reflection_group_name': None, 'orf_route_policy': None, 'origin_as': None, 'remove_private_AS': None, 'route_policy': None, 'route_reflector_client': None, 'send_community_ebgp': None, 'send_community_gshut_ebgp': None, 'send_extended_community_ebgp': None, 'send_multicast_attributes': None, 'weight': None, 'validation': None}]}], 'vrfs': None}, 'state': 'merged', 'running_config': None}}, '_ansible_parsed': True}

changed: [10.104.99.162] => {

    "after": {

        "as_number": "1",

        "neighbors": [

            {

                "address_family": [

                    {

                        "afi": "ipv4",

                        "safi": "unicast",

                        "soft_reconfiguration": {

                            "inbound": {

                                "always": true

                            }

                        }

                    }

                ],

                "neighbor_address": "1.1.1.1"

            }

        ]

    },

    "before": {

        "as_number": "1"

    },

    "changed": true,

    "commands": [

        "router bgp 1",

        "neighbor 1.1.1.1",

        "address-family ipv4 unicast",

        "soft-reconfiguration inbound always"

    ],

    "invocation": {

        "module_args": {

            "config": {

                "as_number": "1",

                "neighbors": [

                    {

                        "address_family": [

                            {

                                "afi": "ipv4",

                                "aigp": null,

                                "allowas_in": null,

                                "as_override": null,

                                "bestpath_origin_as_allow_invalid": null,

                                "capability_orf_prefix": null,

                                "default_originate": null,

                                "long_lived_graceful_restart": null,

                                "maximum_prefix": null,

                                "multipath": null,

                                "next_hop_self": null,

                                "next_hop_unchanged": null,

                                "optimal_route_reflection_group_name": null,

                                "orf_route_policy": null,

                                "origin_as": null,

                                "remove_private_AS": null,

                                "route_policy": null,

                                "route_reflector_client": null,

                                "safi": "unicast",

                                "send_community_ebgp": null,

                                "send_community_gshut_ebgp": null,

                                "send_extended_community_ebgp": null,

                                "send_multicast_attributes": null,

                                "soft_reconfiguration": {

                                    "inbound": {

                                        "always": true,

                                        "inheritance_disable": null,

                                        "set": null

                                    }

                                },

                                "validation": null,

                                "weight": null

                            }

                        ],

                        "neighbor_address": "1.1.1.1"

                    }

                ],

                "vrfs": null

            },

            "running_config": null,

            "state": "merged"

        }

    }

}

META: ran handlers

META: ran handlers

 

PLAY RECAP ******************************************************************************************************************************************************************************

10.104.99.162              : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

 

(ansible_collections) prramoor @ ~/Ansible/iosxr $ 


```




```
RP/0/RSP0/CPU0:ios(config)#show configuration commit list 2

Mon Feb 20 11:28:50.181 UTC

SNo. Label/ID              User      Line                Client      Time Stamp

~~~~ ~~~~~~~~              ~~~~      ~~~~                ~~~~~~      ~~~~~~~~~~

1    commit_label_test_nb  lab       vty0:node0_RSP0_CP  CLI         Mon Feb 20 11:28:19 2023

2    1000000062            lab       con0_RSP0_CPU0      CLI         Mon Feb 20 11:25:20 2023

RP/0/RSP0/CPU0:ios(config)#

RP/0/RSP0/CPU0:ios(config)#

RP/0/RSP0/CPU0:ios(config)#show version        

                                ^

% Invalid input detected at '^' marker.

RP/0/RSP0/CPU0:ios(config)#do show version

Mon Feb 20 11:33:51.484 UTC

Cisco IOS XR Software, Version 6.5.3

Copyright (c) 2013-2019 by Cisco Systems, Inc.

 

Build Information:

 Built By     : ahoang

 Built On     : Tue Mar 26 07:18:24 PDT 2019

 Built Host   : iox-ucs-018

 Workspace    : /auto/srcarchive13/prod/6.5.3/asr9k-x64/ws

 Version      : 6.5.3

 Location     : /opt/cisco/XR/packages/

 

cisco ASR9K () processor

System uptime is 3 days 9 minutes

 
```

**Comment by digitalfiend64** [comment] 2023-02-20 16:45
Thanks @ashwini-mhatre , I'll let the customer know and follow up when I hear back from them.

**Comment by ashwini-mhatre** [comment] 2023-07-03 08:10
@digitalfiend64 Any update?

**Comment by Ruchip16** [comment] 2024-04-10 10:08
@digitalfiend64 closing this as there is no update from the customer, feel free to reopen if the issue still persists.

**Closed by Ruchip16** 2024-04-10 10:08 UTC
Labels: waiting_on_author
