### ISSUE TITLE
iosxr_system:Integration test issue:ConnectionError: unable to connect to socket

### ISSUE THREAD

**Issue by komaldesai13** [ansible-collections/cisco.iosxr#389] opened 2023-05-16 12:57 UTC
##### SUMMARY
When running iosxr_system integration tests from Controller with EE container,
We get an unexpected error "ConnectionError: unable to connect to socket"
On task [ansible.builtin.assert](https://github.com/ansible-collections/cisco.iosxr/blob/main/tests/integration/targets/iosxr_system/tests/netconf/set_lookup_source.yaml#L26)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.iosxr.iosxr_system

##### ANSIBLE VERSION
2.14

##### COLLECTION VERSION
cisco.iosxr 4.0.3

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
Run integration iosxr_system test, the following task failed.
See below the actual results.

##### EXPECTED RESULTS
The task will pass with not errors.

##### ACTUAL RESULTS
TASK [/usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_system : ansible.builtin.assert] ***
task path: /usr/share/ansible/collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_system/tests/netconf/set_lookup_source.yaml:92
fatal: [10.0.149.88]: FAILED! => {
    "msg": "Traceback (most recent call last):\\n  File \\"/usr/lib/python3.9/site-packages/ansible/module_utils/connection.py\\", line 210, in send\\n    response = recv_data(sf)\\n  File \\"/usr/lib/python3.9/site-packages/ansible/module_utils/connection.py\\", line 79, in recv_data\\n    d = s.recv(header_len - len(data))\\nConnectionResetError: [Errno 104] Connection reset by peer\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\"/usr/lib/python3.9/site-packages/ansible/cli/scripts/ansible_connection_cli_stub.py\\", line 315, in main\\n    conn.set_options(direct=options)\\n  File \\"/usr/lib/python3.9/site-packages/ansible/module_utils/connection.py\\", line 194, in __rpc__\\n    response = self._exec_jsonrpc(name, *args, **kwargs)\\n  File \\"/usr/lib/python3.9/site-packages/ansible/module_utils/connection.py\\", line 155, in _exec_jsonrpc\\n    out = self.send(data)\\n  File \\"/usr/lib/python3.9/site-packages/ansible/module_utils/connection.py\\", line 214, in send\\n    raise ConnectionError(\\nansible.module_utils.connection.ConnectionError: unable to connect to socket /home/runner/.ansible/pc/5331dce665. See the socket path issue category in Network Debug and Troubleshooting Guide\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\"/usr/bin/ansible-connection\\", line 33, in <module>\\n    sys.exit(load_entry_point('ansible-core==2.15.0rc2.post0', 'console_scripts', 'ansible-connection')())\\n  File \\"/usr/lib/python3.9/site-packages/ansible/cli/scripts/ansible_connection_cli_stub.py\\", line 318, in main\\n    raise ConnectionError('Unable to decode JSON from response set_options. See the debug log for more information.')\\nansible.module_utils.connection.ConnectionError: Unable to decode JSON from response set_options. See the debug log for more information.\\n"
}

**Comment by ashwini-mhatre** [comment] 2023-05-22 12:36
closing this as not able to reproduce

**Closed by ashwini-mhatre** 2023-05-22 12:36 UTC
